from abc import ABC, abstractmethod
from dataclasses import dataclass, field
import logging
from pathlib import Path
from typing import Dict, Any, List

@dataclass
class PipelineContext:
    """Carries global runtime state, configurations, and logs across pipeline stages."""
    
    # Raw config dictionary read from config.yaml
    config: Dict[str, Any]
    
    # Path of workspace root (where inputs, outputs, cache, etc. are located)
    workspace_dir: Path
    
    # Path to cache root directory (e.g. cache/)
    cache_dir: Path
    
    # Path of active experiment directory (e.g. experiments/experiment_001/)
    experiment_dir: Path
    
    # Configured Logger for output logs
    logger: logging.Logger
    
    # Stage results, mapping stage name to its execution summary
    stage_outputs: Dict[str, Any] = field(default_factory=dict)
    
    # General-purpose state metadata dictionary
    metadata: Dict[str, Any] = field(default_factory=dict)


@dataclass
class StageResult:
    """Captures execution results, performance, and file references from a pipeline stage."""
    
    # Name of the stage
    stage_name: str
    
    # Execution status: True if successful
    success: bool
    
    # Stage duration in seconds
    runtime_seconds: float
    
    # List of paths to files generated by this stage
    output_files: List[Path] = field(default_factory=list)
    
    # Dictionary containing custom outputs or metadata (e.g., width, heights, coordinates)
    metadata: Dict[str, Any] = field(default_factory=dict)
    
    # Error message if success is False
    error_message: str = ""


class BaseStage(ABC):
    """Abstract base class establishing the contract for all pipeline stages.

    Each pipeline stage must implement `run` containing the stage execution logic
    and `is_cached` verifying if the execution can be skipped.
    """

    def __init__(self, name: str) -> None:
        """Initializes a new stage.

        Args:
            name: The name of the pipeline stage.
        """
        self.name: str = name

    @abstractmethod
    def run(self, context: PipelineContext) -> StageResult:
        """Executes the operations of this stage.

        Args:
            context: The shared PipelineContext instance.

        Returns:
            A StageResult detailing success status and metadata.
        """
        pass

    @abstractmethod
    def is_cached(self, context: PipelineContext) -> bool:
        """Verifies if the outputs from a previous execution are cached and valid.

        Args:
            context: The shared PipelineContext instance.

        Returns:
            True if valid cache files exist and we can resume past this stage.
        """
        pass
